### ISSUE TITLE
How does the deployed Docker container authenticate access to CONFIG_BUCKET?

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/backend-service-pattern#2]
As far as I understand, the point of calling `getconfig.sh` from `docker-entrypoint.sh` is to ensure that the Docker container image doesn't contain any secrets when it's built, but rather that the Docker container harvests its secrets by downloading them from the `project_config.py` file from the CONFIG_BUCKET as the container is starting up (e.g. s3://hacko-homeless-config/integration/project_config.py).

Now that I understand how this works, I have a question: how does the AWS-deployed container actually authenticate to the CONFIG_BUCKET in the first place?

In all my testing from my laptop and from Travis, if I didn't have AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY populated (or equivalent), the `aws s3 cp` command would fail miserably.

How does the Docker container (devoid of secrets) provide AWS authentication context to the S3 bucket?  I can't find any trace of where we're baking the AWS creds into the container image (nor would I want to).

Does a container running in ECS inherit a security context from ECS?  How can we know what that security context is, so that we can lock down the permissions on the S3 buckets and not have to leave them open to all AWS authenticated users?

**Comment by pdxdiver** [comment]
This is why.  ECS Cluster has an IAM Role that allows it to get s3 Objects.  
```json

         - PolicyName: ecs-service
                  PolicyDocument: |
                    {
                        "Statement": [{
                            "Effect": "Allow",
                            "Action": [
                                "ecs:CreateCluster",
                                "ecs:DeregisterContainerInstance",
                                "ecs:DiscoverPollEndpoint",
                                "ecs:Poll",
                                "ecs:RegisterContainerInstance",
                                "ecs:StartTelemetrySession",
                                "ecs:Submit*",
                                "logs:CreateLogStream",
                                "logs:PutLogEvents",
                                "ecr:BatchCheckLayerAvailability",
                                "ecr:BatchGetImage",
                                "ecr:GetDownloadUrlForLayer",
                                "ecr:GetAuthorizationToken",
                                "s3:GetObject"
                            ],
                            "Resource": "*"
                        }]
                    }

```

**Comment by MikeTheCanuck** [comment]
Nice - thanks for closing the loop on this
